### ISSUE TITLE
Missing indexMetadata.json file in var folder

### ISSUE THREAD

**Issue by jay7793** [DivanteLtd/pimcore2vuestorefront#9]
I am a beginner in this project. I tried manually dump products using the `node index.js new` command in the /src folder, but I'm having trouble finding the file. /var/indexMetadata.json I want to know where this file can be found? And why do not I have the /var folder already?

Thanks in advance

**Comment by pkarw** [comment]
You need  to go thru setup plus run initial import with:

git clone https://github.com/DivanteLtd/pimcore2vuestorefront.git p2v
cd p2v
npm install
node setup.js

Otherwise the indexMetadata file won’t be created

**Comment by jay7793** [comment]
Thank you. I understand.
